name: A workflow for my Hello World file
on: 
  push:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
